### ISSUE TITLE
Improve Settings page UX

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#131]

**Comment by mattyg** [comment]
I think the simplest change is sort by order:
- add an integer field 'order' to SettingsModel & PeriodSettingsModel, and their associated types
- sort the settings fields by their 'order' on the frontend

And the next simplest change is to group by category:
-  add a new db collection 'settingscategories' to specify the categories
- add a ref field 'category' to SettingsModel and PeriodSettingsModel
- group the settings fields by their category on the frontend, and sort by order within their groups

**Comment by kristoferlund** [comment]
editor.formatOnSave
