### ISSUE TITLE
Self praise - I did a thing

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#132]

**Comment by Vyvy-vi** [comment]
Would this be a separate command inside the discord, or does this run off of the `/praise` command?
(if we're making a distinction for self-praise, would the PraiseModel also reflect a distinction?)

**Comment by kristoferlund** [comment]
Most likely a separate command. This requires some thought and discussion before implementation. But in general I, believe the way to go when it comes to commands is to add more commands rather than adding more complex options to commands. Why, because that is easier for the end users.

The exception would be a `/praise-admin` command where we definitely could add subcommands, options etc.

**Comment by mattyg** [comment]
Just a note that the system currently allows self praise, simply by running `/praise receivers: @myuseraccount`

If we *don't* want to allow this yet, we might want to disable that functionality.

I think there is some discussion needed / concerns about this feature. We may want to collect our thoughts here.

**Comment by Vyvy-vi** [comment]
This issue could be closed since we added a setting that allows self-praise to be toggled, which resolves the scope of this issue.

**Comment by kristoferlund** [comment]
Agreed. Closing.
