### ISSUE TITLE
Sanitise reason content string returned by discord

### ISSUE THREAD

**Issue by Vyvy-vi** [commons-stack/praise#156]
Discord return's channel mentions, user mentions, emotes and role mentions as formatted snowflakes inside the content string.
This breaks the context in people's praise.
![](https://cdn.discordapp.com/attachments/895054667921379331/952993162094317588/Screenshot_2022-03-14_at_11.43.22_PM.png)

**Comment by kristoferlund** [comment]
Perhaps we could store both the original id and the current name for display purposes? That would require us to come up with our own custom format, perhaps adding a colon and the current name? 
```
<#098098080087087:params>
```

**Comment by kristoferlund** [comment]
Add field rawReason

```
export interface Praise {
  reason: string;
  rawReason: string;
}
```

Process incoming praise, replace discord tags with actuakl usernames/channel names etc.

```
Praise {
  reason: "for discussing with mitch#1234"
  rawReason: "for discussing with <#098098080087087>";
}
```

Process all database in migration.

**Comment by mattyg** [comment]
> Add field rawReason
> 

Just a note that we could name the fields 'reason' (for the raw value) and 'reasonRealized' (for the formatted value) to match the naming used in the SettingsModel.

**Comment by kristoferlund** [comment]
```
Praise {
  reasonRealized: "for discussing with mitch#1234"
  reason: "for discussing with <#098098080087087>";
}
```

- Migration only changes the schema
- Make a script that processes the TEC database
  - https://github.com/CommonsBuild/tec-rewards/blob/main/initial-import/discord_ids.csv
