### ISSUE TITLE
add FAQ to sidebar in praise dashboard 

### ISSUE THREAD

**Issue by divine-comedian** [commons-stack/praise#219]
We get a lot of 1 off questions - it would be good to identify and answer some of the most common questions from quantifiers right in the UI without making them scan through 3-4 forum posts looking for answers. 

![image](https://user-images.githubusercontent.com/67759413/161167381-91026fff-6739-406f-8a81-2dd09ab26c77.png)

I suggest we can make a simple JSON file with questions and answers in them - we could toggle the FAQ off or let new orgs build their own JSON that populates the FAQ page - here is an example from https://giveth.io/faq

![image](https://user-images.githubusercontent.com/67759413/161167127-6dbf8561-8d2b-4552-8668-23562950b0c8.png)

**Comment by kristoferlund** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/9698363/165807372-223a6d67-20d0-4ddc-8173-5cf7bf8151e7.png">

Plus the ability to toggle sections.

**Comment by kristoferlund** [comment]
https://headlessui.dev/react/disclosure

<img width="486" alt="image" src="https://user-images.githubusercontent.com/9698363/166694429-d42beda4-01e2-4de7-976c-a599a3d18667.png">
