### ISSUE TITLE
Option to limit praising to a certain discord channel

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#264]
We need to be able to specify:
- Allow praising in all channels
- No channels, the bot effectively turned off
- Some channels - which channels

**Comment by kristoferlund** [comment]
New settings:
- PRAISE_ALLOWED_IN_ALL_CHANNELS: boolean
- PRAISE_ALLOWED_CHANNEL_IDS: List of channel ids

**Comment by kristoferlund** [comment]
@nebs-dev have you begun working on this? @Vyvy-vi would like to take a look at it otherwise.

**Comment by nebs-dev** [comment]
> 

i started looking at it but than moved to other issues.. so he can take over if he wants

**Comment by kristoferlund** [comment]
The conclusion of the discussion we had today was: Don't implement the bot commands for administration yet. It is out of scope as of now and needs more detailed specs before going ahead. 

I opened up a new issue, @Vyvy-vi if you will, please describe how you would like to set it up here: #449
