### ISSUE TITLE
System activity log

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#309]
For transparency we should log and show important events in the system.

```
2022-04-01 10:02 – Mitch#1234 added the ADMIN role to kristofer#1234
2022-04-01 10:05 – Vyvy-vi#1234 closed period: "November 2021" 
```

Log would be made accessible from the main navigation.

**Comment by kristoferlund** [comment]
@mattyg @Vyvy-vi @nebs-dev Which events should we log?

**Comment by mattyg** [comment]
I think I would log all database writes. Then we can add filtering for what is displayed on the front-end.

**Comment by kristoferlund** [comment]
The only reason not to would be database size concerns I guess?

**Comment by kristoferlund** [comment]
@Vyvy-vi noted that we might want to base logging on "user events" instead of database writes. Example: A failed praise attempt is never written to the database but is an event worth logging.
