### ISSUE TITLE
Integrate metrics and graphs in the Praise dashboard

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#351]

**Comment by kristoferlund** [comment]
@Vyvy-vi takes a look at [PyScript](https://www.anaconda.com/blog/pyscript-python-in-the-browser) and other solutions.

Will we use this in production? This is what the creators say 😄 

> While it is still unstable and limited, it does actually work!

Simple static bokeh plot example: https://pyscript.net/examples/bokeh.html

**Comment by mattyg** [comment]
I'd like to share this in case people haven't seen it before. It's a perspective I share: https://mcfunley.com/choose-boring-technology

**Comment by kristoferlund** [comment]
Fully support that as well! That is why we initially chose to develop the backend on Java/Spring framework. Not sexy new tech.

**Comment by kristoferlund** [comment]
- TypeScript
- Find a good chart library (old, stable, being maintained)
- Backend does the analysis
- Frontend styles the data
- Most queries most likely can be performed using mongoose queries
- Analysis for periods as well as "cross period analysis"
- Period analysis
  - Number of praise this period
  - Total praise score
  - No of receivers / givers 
- Cross period analysis
  - Total users 
  - Total active users (need definition)
  - Praise per week
- Filters
  - By discord channel (who sent which praise where) 
- API endpoint
  - Separate endpoints for period stats and cross period stats
    - All: `/api/period/{id}/stats/all´
    - Single: `/api/period/{id}/stats/{analysis key}´
  - Analysis key being: `top10praisereceivers` or similar
 
These are some notes after conversation with @Vyvy-vi. We need to do a Miro board session together to design this feature.
