### ISSUE TITLE
Display calculated score of praise marked as duplicate

### ISSUE THREAD

**Issue by mattyg** [commons-stack/praise#378]
Currently when praise is marked as duplicate, the original praise slider is adjusted, while the duplicate sliders move to '0' and are disabled. 

This has caused some confusion for quantifiers. See this message from liviade on TEC discord:

> 1. marking duplicates using the new button isn't quite working. The value of the quantified praise goes to 0 when I select them both. 

We should make the UX of praise marked duplicate more clear by removing the slider entirely, and replacing it with a text box that indicates the calculated score it will receive.

**Comment by kristoferlund** [comment]
What if we would show Praise scores for **all** Praise on the quant page, similar to on the praise details page?

<img width="664" alt="image" src="https://user-images.githubusercontent.com/9698363/169135850-43c3f6fb-8379-4014-89f3-11a5578a71ee.png">

Then the slider could remain grayed out like now. For now. Remember, a UI polish/upgrade is coming later.
