### ISSUE TITLE
Very slow rendering of component 'PeriodMessage' in 'QuantifyPeriodReceiverPage'

### ISSUE THREAD

**Issue by mattyg** [commons-stack/praise#379]
Liviade from TEC discord reported the following issue while quantifying:

> 2. Name and info about the receiver are taking aprox 30 seconds to load. 

I believe the slow component is `PeriodMessage` in the `QuantifyPeriodReceiverPage`.

That component runs the following recoil callbacks:
- usePeriodQuantifierPraiseQuery
- useAllPeriodSettingsQuery

It also runs the following recoil selectors:
- PeriodQuantifierReceivers(periodId)
- PseudonymForUser(periodId, userId)

We will have to investigate which of these are the culprit(s) for making the rendering so slow, and determine possible refactors to improve performance.

**Comment by kristoferlund** [comment]
The UI has been feeling more sluggish since we switched to running everything on Docker. Coincidence perhaps?

**Comment by mattyg** [comment]
> The UI has been feeling more sluggish since we switched to running everything on Docker. Coincidence perhaps?

It looks like the server CPUs are running at 100% consistently (~80% from the api) -- might make sense to bump it up a hardware tier.

That said I don't see any reason that this one component should be so much slower than any other. There's definitely a front-end issue.

**Comment by kristoferlund** [comment]
CPU issue resolved.
