### ISSUE TITLE
Praise bot admin notifications potentially being sent twice

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#384]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/9698363/167939896-7d2832d7-bfd8-4d5e-9697-ee2d1394f232.png">

**Comment by Vyvy-vi** [comment]
I wasn't able to reproduce this.
My guess is that the admin clicked on the Continue button twice.

Currently, these buttons don't get disabled when pressed. Maybe, we should open a new issue for discussing that?

![Screenshot 2022-06-04 at 12 32 14 AM](https://user-images.githubusercontent.com/62864373/171931238-cd2236f0-474e-4d76-a0f5-229de48bac3b.png)
