### ISSUE TITLE
Whoami command says user does not have praise powers, when they do

### ISSUE THREAD

**Issue by mattyg** [commons-stack/praise#419]
Reported by `@rex` on TEC discord:
> btw the whoami text says I don't have praise powers but I do, inconsequential bug but bug nonetheless

**Comment by Vyvy-vi** [comment]
I think this is due to the recent update in the TEC server where we removed the requirement for having the "Praise Giver" role. The bot doesn't account for cases when there is no valid value for the `PRAISE_GIVER_ROLE_ID`
