### ISSUE TITLE
dark mode for praise dashboard

### ISSUE THREAD

**Issue by divine-comedian** [commons-stack/praise#420]
for those of us who stay up late at night quantifying praise, it would be cool to have a dark mode available. Right now it is very bright and white! 

This was given as some feedback from quantifiers during the previous review call.

**Comment by kristoferlund** [comment]
Yes, for sure we would like to do that.

**Comment by pkretzschmar** [comment]
@kristoferlund just some [docs](https://tailwindcss.com/docs/dark-mode) from tailwind on how to implement dark mode
