### ISSUE TITLE
Unable to connect using Ledger Live

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#510]
Most likely this is an issue with RainbowKit, issue can be confirmed at https://www.rainbowkit.com/.

![image](https://user-images.githubusercontent.com/9698363/176854038-21c3e2c2-fd41-4876-afa5-1ba2e04b1f54.png)

See also: https://github.com/rainbow-me/rainbowkit/issues/382

**Comment by Maindefi** [comment]
Have you rectified your wallet?

**Comment by kristoferlund** [comment]
Update to latest versions of Rainbow / wagmi and see if this is still an issue.
