### ISSUE TITLE
BUG: First time praise message duplication

### ISSUE THREAD

**Issue by Vyvy-vi** [commons-stack/praise#552]
The first time praiser messags is sent even when the praise is an error.
Is that desirable behaviour?

<img width="704" alt="Screenshot 2022-08-19 at 1 45 48 PM" src="https://user-images.githubusercontent.com/62864373/185575611-d07af19d-9329-4375-818f-b59c0e891892.png">

**Comment by kristoferlund** [comment]
Yeah, I noticed that as well the other day. No, I'd say that is not expected behaviour. Message should only be sent on successful praise. Moving to product backlog.
