### ISSUE TITLE
Upgrade Instructions link is wrong on release link

### ISSUE THREAD

**Issue by kkatusic** [commons-stack/praise#560]
On version page: https://github.com/commons-stack/praise/releases link to **Upgrade Instructions**  leads nowhere.

Link: https://givepraise.xyz/docs/setup/upgrade-praise

Suggestion solution: maybe wright link is: https://givepraise.xyz/docs/server-setup/upgrade-praise

**Comment by kristoferlund** [comment]
Thank you, I missed that. Now resolved.
