### ISSUE TITLE
App logo should not disappear on system upgrade

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#564]
Uploaded files need to be stored outside of the Docker container so that the persist over version upgrades.

**Comment by kkatusic** [comment]
As I can see `Logo` has been saved in database, settings table. If you run `bash upgrade.sh` it disappear from uploads directory? Am I wright @kristoferlund ? How I can produce that bug?

**Comment by kristoferlund** [comment]
Yeah.. sort of. :) But, upgrade script only upgrades if there are new docker images to be fetched from GitHub. I'll find the code location of the problem.

**Comment by kristoferlund** [comment]
This folder is the upload folder:

https://github.com/commons-stack/praise/tree/main/packages/api/uploads

It gets copied into the Docker container when that is built. Then, uploaded files are being served by the Express API server.

https://github.com/commons-stack/praise/blob/7ffe7b24677f9a4a1a79e978304c925993fcdfb8/packages/api/src/server.ts#L85

The upload folder cannot be indside the Docker container but should be outside of it. The api `Dockerfile` needs to be configured to make that happen.

https://github.com/commons-stack/praise/blob/main/packages/api/Dockerfile

Or.. perhaps it is configured in the `docker-compose` file.

https://github.com/commons-stack/praise/blob/main/docker-compose.production.yml

**Comment by kkatusic** [comment]
I found where it has been stored, and figured it out after I ask you. I checked the code and what I can understand for now when the update is done it overwrites the folder "inside" API container with default files and it serves image that doesn't exist.

Maybe we can omit that folder from the update, better to say omit it from `docker-compose`, put it in its volume, found one answer that is related to this: https://stackoverflow.com/a/38601156/917827 .

**Comment by kristoferlund** [comment]
I think we need to configure a docker volume outside of the container. I think that can be setup from within the docker-compose file.

**Comment by kkatusic** [comment]
Yes it can, you can define volumes inside docker-compose yaml file.

**Comment by kristoferlund** [comment]
Replace this: 

https://github.com/commons-stack/praise/blob/bfa5500d0e8034120901835f026d0eb386bc0798/packages/api/src/shared/functions.ts#L68

https://www.youtube.com/watch?v=Wh4BcFFr6Fc&t=889s

**Comment by kkatusic** [comment]
@kristoferlund please check [fix/api_uplo](https://github.com/commons-stack/praise/tree/fix/api_upload_dir)

**Comment by kkatusic** [comment]
As I said this morning I tried to run images in my local Docker containers but problem exist with FrontEnd image. It has been using same port as my local apache server, but I also tried to run that image with custom ports:

![docker-container](https://user-images.githubusercontent.com/1242145/191587386-a20a8c61-8ea2-4bf9-b6dc-70390e27dda1.jpg)
 
but getting a new error: ` 2022/09/21 18:53:55.572 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
run: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized global option: handle`

@kristoferlund I will wait your try.

**Comment by kkatusic** [comment]
@kristoferlund did you test this?

**Comment by kristoferlund** [comment]
Yup, it worked but I had to add some small things. Have a look at #604

**Comment by kkatusic** [comment]
> Yup, it worked but I had to add some small things. Have a look at #604

You changed several files :D
