### ISSUE TITLE
Display custom emojis with the correct size

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#568]
Custom emojis are regular images in praise items. These images need to have the correct size.

❌
<img width="807" alt="image" src="https://user-images.githubusercontent.com/9698363/187267315-9d26cf97-2846-4b19-86da-8de8843dc17d.png">

✅
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/9698363/187267561-abfda811-d905-4d9e-ac02-3818faa0b0e3.png">

**Comment by kkatusic** [comment]
@kristoferlund can you provide me raw code for that message, I will put it in one of existing testing data and check it? Thx

**Comment by kristoferlund** [comment]
So, this praise:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/9698363/189964342-162b4abc-ebc3-44cf-98ba-cd136ec2238d.png">

Looks like this on the dashboard:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/9698363/189965069-77b299d3-d86e-4221-8a71-8bb9b6fcd7c6.png">

This is the raw content - reason & reasonRealized:

`for being <:avatar_2:1018890903148056696>`

This is the processed reason after calling `getMarkdownText`:

`for being <img class="d-emoji" src="https://cdn.discordapp.com/emojis/1018890903148056696.png" alt=":avatar_2:">`

**Comment by kkatusic** [comment]
Before: https://skitch.kkatusic.com/before_28D4A89E.png
After: https://skitch.kkatusic.com/after_28D4ADF7.png

First thx for helping me with raw code, I attached to do existing message and than look out what is happening.
`getMarkdownText` is using library **discord-markdown** to parse text with discord data, like images, emojis, users... and I check that functions and properties but it hasn't option to attach additional css class or style to some element in parser function, like author said: https://github.com/brussell98/discord-markdown/issues/35#issuecomment-1157783783

I made one approach make parse after parse and add some Tailwindcss classes, maybe it isn't best solution, but everyone can suggest better solution.

Fix: https://github.com/commons-stack/praise/compare/fix/custom_emoji_img_size?expand=1
