### ISSUE TITLE
Admin should be able to reset settings to default values in the praise dashboard settings interface

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#580]
- On hover on the title of a setting, an icon button appears that allows an admin to reset a setting to the default value: <img width="926" alt="image" src="https://user-images.githubusercontent.com/9698363/192223940-f80ac22d-72b0-4955-9d5d-b5766e9dea3d.png">
- Button looks and works similar to the quantifier replacement button: <img width="697" alt="image" src="https://user-images.githubusercontent.com/9698363/192222604-09e620a5-edde-4eef-be81-3d5bc3522b60.png">
- Add `defaultValue` to API interface `Setting` and `SettingDto`.
- Populate all default values using a database migration
- Use the `/settings/:id/set` to reset value, or create new endpoint `/settings/:id/reset`

**Comment by kristoferlund** [comment]
@kkatusic I added som detail to this issue, see 👆👆

**Comment by kkatusic** [comment]
@kristoferlund I changed icon/button behaviour and find some tiny bug, please remove last migration and re-test, thx
