### ISSUE TITLE
Make search inputs look better in dark mode

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#587]

**Comment by kristoferlund** [comment]
Light mode: 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/9698363/190219477-af31593d-6990-45bd-805a-c7b1bbf94c1d.png">

Dark mode:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/9698363/190219340-12cbf0ba-99aa-4fd9-86ef-67313a1d1be6.png">

Search boxed also exist on other pages:
- User page
- Quantification page
- .. possibly elsewhere

**Comment by kkatusic** [comment]
@kristoferlund you can check fix here: https://github.com/commons-stack/praise/compare/fix/search_input?expand=1
