### ISSUE TITLE
Minimise the permissions we require for the Discord Bot

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#627]
We give the bot really broad permissions, many of which we don't use. When clients ask we must be able to motivate why we require certain permissions. 

Let's make sure we require only what we need.

```
https://discord.com/api/oauth2/authorize?client_id=<CLIENT ID>&permissions=378561611840&scope=bot%20applications.commands
```

**Comment by Vyvy-vi** [comment]
This is very much needed 👍
Though, I think we should add some commands to the bot in order to allow server admins to provide perms to the bot(like allowing it to join a private thread or channel) _before_ we reduce the permission set used by the bot.

**Comment by Vyvy-vi** [comment]
We could update the docs with this link: https://discord.com/api/oauth2/authorize?client_id=627772985872220161&permissions=274878023680&scope=bot%20applications.commands

**Comment by kristoferlund** [comment]
Changed the link in the docs website: https://github.com/commons-stack/praise-web/commit/65f33401953dacbdae44358cbafa50d0eac498ad
