### ISSUE TITLE
RainbowKit causes 429 HTTP error for unknown reason

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#643]
![image](https://user-images.githubusercontent.com/9698363/197714319-a06dcfe4-691b-4e1c-b7ec-15cabc8bc5bf.png)

**Comment by kristoferlund** [comment]
@kkatusic 

There is a new library that at least looks more light weight than RainbowKit. It still uses Wagmi under the hood.

https://docs.family.co/connectkit#connectkit

But, it also recommends adding your own Infura/Alchemy key.

**Comment by kkatusic** [comment]
Maybe this will disappear when we update version of the RainbowKit.

I think that RainbowKit for some reasons checking "eth_blockNumber" in ETH network via AJAX link:

https://eth-mainnet.alchemyapi.io/v2/_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC

<img width="786" alt="Screenshot 2022-11-03 at 23 21 05" src="https://user-images.githubusercontent.com/1242145/199845746-38eab948-4d01-4354-a23f-bd868e4d7566.png">

and provided link is using public API key that is only for test. If you see link it is related to [Alchemy](https://www.alchemy.com/), it is eth node which serve you some data from eth network. If you use some node, it use some resources and you on Alchemy can open new project and request API key. You will have few millions free requests.

But we can wait first update

**Comment by kkatusic** [comment]
@kristoferlund you can also close this one issue, it's has been solved with new versions RainbowKit and Wagmi package
